### ISSUE TITLE
Support multiple sort descriptors

### ISSUE THREAD

**Issue by jimix** [jimix/CDTDatastore#29]
This [code](/jimix/CDTDatastore/blob/518a9fc0e82791c720fb25b0a28fc7091e535937/Classes/common/CDTIncrementalStore.m#L1813-1815)

``` objc
        if (sds.count > 1) {
            oops(@"not sure what to do here");
        }
```

Should be supportable

**Comment by jimix** [comment]
@mkistler it looks like this is solved in:
https://github.com/cloudant/CloudantQueryObjc/blob/master/README.md
Which should get merged in the next couple of weeks.

Here is the announcement from the mailing list:
https://groups.google.com/forum/#!topic/cloudant-sync/uMhy51KtPF4

Also https://github.com/cloudant/CloudantQueryObjc/blob/master/README.md#creating-indexes claims support for sub documents:

> To index values in sub-documents, use dotted notation.

I got this info from @tomblench and it is being worked on by @alfinkel
care to investigate?

**Comment by mkistler** [comment]
@jimix you are correct.  CloudantQuery does support multiple sort descriptors, so this item is now a dup of issue #33
