### ISSUE TITLE
Add support for batch update requests

### ISSUE THREAD

**Issue by mkistler** [jimix/CDTDatastore#30]
Apple added the ability to perform batch updates on CoreData MOCs in iOS 8.  The basics are described in the WWDC 2014 talk #225 "What's new in Core Data", but the online docs are horribly behind and it's difficult to find any "official" documentation on the feature.

In the WWDC talk, it looks like the batch update request is performed at the DB level, since Apple touted the performance improvement of batch updates over traditional update requests that must pull each object into the MOC, make the change, and then store it back to the DB.

It is unlikely that Cloudant gives an interface for doing batch updates on the DB, so here we just want get the functionality of batch updates so that applications work properly.  The implementation can switch to a DB-level update if/when Cloudant offers that capability.

**Comment by mkistler** [comment]
This [slashdot post](http://stackoverflow.com/questions/24955709/bulk-update-data-in-ios-7-coredata) suggests how the bulk update is done at the DB.

**Comment by jimix** [comment]
closed by PR #36
